repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
        # The JSONs below support comments (against spec)
        exclude: ^(.eslintrc.json|tsconfig.json)
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer

    # Changes tabs to spaces
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
      - id: remove-tabs
        exclude: "(^(.git|setup.cfg))|(.(json|scn)$)"

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.2.0
    hooks:
      - id: pretty-format-ini
        args: [--autofix]
      - id: pretty-format-toml
        args: [--autofix]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black

    # Prettier (HTML, JS, CSS, Markdown, YAML…)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
